Update getchangedfiles.yml

diff --git a/.github/workflows/getchangedfiles.yml b/.github/workflows/getchangedfiles.yml
--- a/.github/workflows/getchangedfiles.yml
+++ b/.github/workflows/getchangedfiles.yml
@@ -36,4 +36,35 @@ jobs:
             fi            
             fi
           done
-          echo $res
+          echo $res > ./FILE_DIFF.txt
+          
+    # Checkout the source code
+      - name: 'Checkout source code'
+        uses: actions/checkout@v2
+        
+    # Install Salesforce CLI
+      - name: 'Install Salesforce CLI'
+        run: |
+                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+                  mkdir ~/sfdx
+                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+                  ~/sfdx/bin/sfdx version
+                  
+      # Store secret for acc org
+      - name: 'Populate auth file with ACC_SFDX_URL secret'
+        shell: bash
+        run: |
+                  echo ${{ secrets.ACC_SFDX_URL}} > ./ACC_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./ACC_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing ACC_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
+      # Authenticate acc
+      - name: 'Authenticate Acc'
+        run: sfdx auth:sfdxurl:store -f ./ACC_SFDX_URL.txt -a meeraacc -d
+              
+      # Deploy source to Acc org
+      - name: 'Push source to Acc org'
+        run: sfdx force:source:deploy -u meeraacc@gmail.com -p ./FILE_DIFF.txt
